PROGRAM HttpResponse(INPUT, OUTPUT);
USES
  DOS;
BEGIN
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITE('CONTENT_LENGTH: ');
  WRITELN(GetENV('CONTENT_LENGTH'));
  WRITE('REQUEST_METHOD: ');
  WRITELN(GetEnv('REQUEST_METHOD'));
  WRITE('QUERY_STRING: ');
  WRITELN(GetEnv('QUERY_STRING'));
  WRITE('HTTP_USER_AGENT ');
  WRITELN(GetEnv('HTTP_USER_AGENT'));
  WRITE('HTTP_HOST: ');
  WRITELN(GetEnv('HTTP_HOST'));
END.
