PROGRAM HttpResponse(INPUT, OUTPUT);
USES 
  GPC;
BEGIN{PROGRAM HttpResponse}
  WRITELN('CONTENT_LENGTH: ');
  WRITE(GetEnv('CONTENT_LENGTH'));
  WRITELN('REQUEST_METHOD: ');
  WRITE(GetEnv('REQUEST_METHOD'));
  WRITELN('QUERY_STRING: ');
  WRITE(GetEnv('QUERY_STRING'));
  WRITELN('HTTP_USER_AGENT: ');
  WRITE(GetEnv('HTTP_USER_AGENT'));
  WRITELN('HTTP_HOST: ');
  WRITE(GetEnv('HTTP_HOST'))
END. {PROGRAM HttpResponse}
